services:
  database:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=expenses
      - POSTGRES_PASSWORD=beyondTheSystem
      - POSTGRES_DB=expenses
volumes:
  pgdata: